DATASET:
  TRAIN_PATH: "./dataset/new_train"
  TEST_PATH: "../dataset/test"

SAM:
  CHECKPOINT: "./sam_vit_b_01ec64.pth"
  RANK: 4

TRAIN:
  BATCH_SIZE: 2
  NUM_EPOCHS: 50

TEST:
  IMAGE_PATH: "./dataset/new_train/images/ring4.jpg"
  BBOX: [13, 46, 210, 197]