DATASET:
  TRAIN_PATH: "./dataset/new_train"
  TRAIN_IMAGE_PATH: "../dataset/train"
  TRAIN_MASK_PATH: "../dataset/train"
  TEST_PATH: "../dataset/test"

SAM:
  CHECKPOINT: "./sam_vit_b_01ec64.pth"
  RANK: 8

TRAIN:
  BATCH_SIZE: 2
  NUM_EPOCHS: 200

TEST:
  IMAGE_PATH: "../bottle_glass_dataset/test/perfume2.jpg"
  BBOX: [307, 107, 646, 925]