DATASET:
  FOLDER_PATH: "../bottle_glass_dataset"

SAM:
  CHECKPOINT: "./sam_vit_b_01ec64.pth"
  RANK: 4

TRAIN:
  BATCH_SIZE: 2
  NUM_EPOCHS: 1

TEST:
  IMAGE_PATH: "../bottle_glass_dataset/test/perfume2.jpg"
  BBOX: [307, 107, 646, 925]